### ISSUE TITLE
problem with incorrect message

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/reference#1]
At first, thank you for this plugin. It works (tested on localhost), I had problem only with one thing.
It always returns error message although everything was saved correctly.

![image](https://cloud.githubusercontent.com/assets/5429548/17649769/d038d216-623c-11e6-81ee-f52580a98e6c.png)

I found the reason in mysql_class.php . When I vardump result (something like this)
![image](https://cloud.githubusercontent.com/assets/5429548/17649779/fdfe2e62-623c-11e6-80e3-9aa3e54faae9.png)
result is  bool(true) so it never pass test above.

**Comment by CaMer0n** [comment]
@Jimmi08 Thanks for this. Are you using PDO or not for MySQL?

**Comment by CaMer0n** [comment]
I reproduced the problem using PHP 5.4. It should be fixed in the core now.

**Comment by Jimmi08** [comment]
Not at all. Is possible that e_admin.php doesn't work with download plugin? I've got it works with pages, links_page plugin, but not with download. Thanks

**Comment by CaMer0n** [comment]
The downloads plugin isn't using e_admin for it's edit page, but a custom form instead. It's a hybrid between old and new code.

**Comment by Jimmi08** [comment]
Thanks, I wasn't sure.
